background {
    color = rgba(2B253Bee)
    path = /usr/share/backgrounds/okonomi/wallpaper.png
    blur_passes = 1
}

input-field {
    monitor =
    size = 1650, 100
    position = 0, 100
    halign = center
    valign = center

    outer_color = rgba(483c69ff) 
    check_color = rgba(6a5d8cff) 

    outline_thickness = 10
    rounding = 0
    placeholder_text = 
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
}

animations {
    enabled = false
}
